import HeroSection from '@/components/Homepage/HeroSection';
import RootLayout from '@/components/layouts/RootLayout';
import Head from 'next/head';

const HomePage = () => {
  return (
    <>
      <Head>
        <title>PC Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div> 
      <HeroSection/>
      </div>
    </>
  );
};

HomePage.getLayout = function getLayout(page) {
  return <RootLayout>{page}</RootLayout>;
};

export default HomePage;
